spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  application:
    name: web-api
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/mediasoft_db
#    username: postgres
#    password: 1
#  datasource:
#    url: jdbc:h2:mem:testdb;NON_KEYWORDS=value
#    driver-class-name: org.h2.Driver
logging:
  level:
    org:
      springframework:
        web=DEBUG:

server:
  port: 80
  servlet.context-path: /
  tomcat:
    max-swallow-size: 20MB
    max-http-form-post-size: 20MB